package bean;
// Generated Oct 24, 2016 5:01:11 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * DosenWali generated by hbm2java
 */
public class DosenWali  implements java.io.Serializable {


     private String nik;
     private String nama;
     private String alamat;
     private Set mahasiswas = new HashSet(0);

    public DosenWali() {
    }

	
    public DosenWali(String nik, String nama, String alamat) {
        this.nik = nik;
        this.nama = nama;
        this.alamat = alamat;
    }
    public DosenWali(String nik, String nama, String alamat, Set mahasiswas) {
       this.nik = nik;
       this.nama = nama;
       this.alamat = alamat;
       this.mahasiswas = mahasiswas;
    }
   
    public String getNik() {
        return this.nik;
    }
    
    public void setNik(String nik) {
        this.nik = nik;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public Set getMahasiswas() {
        return this.mahasiswas;
    }
    
    public void setMahasiswas(Set mahasiswas) {
        this.mahasiswas = mahasiswas;
    }




}


