package bean;
// Generated Oct 24, 2016 5:01:11 PM by Hibernate Tools 3.6.0



/**
 * Mahasiswa generated by hbm2java
 */
public class Mahasiswa  implements java.io.Serializable {


     private String nim;
     private DosenWali dosenWali;
     private String nama;
     private String alamat;

    public Mahasiswa() {
    }

    public Mahasiswa(String nim, DosenWali dosenWali, String nama, String alamat) {
       this.nim = nim;
       this.dosenWali = dosenWali;
       this.nama = nama;
       this.alamat = alamat;
    }
   
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }
    public DosenWali getDosenWali() {
        return this.dosenWali;
    }
    
    public void setDosenWali(DosenWali dosenWali) {
        this.dosenWali = dosenWali;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }




}


